// Auto-generated from roadmap.yaml -- DO NOT include PHI
import { Workstream, RoadmapTask, Milestone, RiskItem, DecisionItem } from "./roadmapTypes";

export const MOCK_WORKSTREAMS: Workstream[] = [
  { id: "WS-CLIN", label: "Clinical Workflow", purpose: "Define how EndoScribe and PEPRisc fit into ERCP workflow, including prospective shadow-mode versus clinician-facing use.", owner: "", status: "active" },
  { id: "WS-PLATFORM", label: "EndoScribe Platform", purpose: "Build the core transcription, structured note, variable extraction, logging, and dashboard platform.", owner: "", status: "active" },
  { id: "WS-PEP", label: "PEPRisc Integration", purpose: "Integrate PEPRisc as the first clinical prediction module within EndoScribe.", owner: "", status: "active" },
  { id: "WS-AUDIO", label: "Audio Capture / Microphones", purpose: "Compare phone microphones, OR-level microphones, and room setups for reliable endoscopy-suite audio capture.", owner: "", status: "active" },
  { id: "WS-ASR", label: "ASR / Transcription", purpose: "Evaluate Whisper, Med-ASR-type systems, and other medical ASR options for ERCP speech.", owner: "", status: "active" },
  { id: "WS-DIAR", label: "Speaker Diarization", purpose: "Isolate the primary endoscopist voice from multi-speaker room audio and cross-talk.", owner: "", status: "active" },
  { id: "WS-DATA", label: "Data Curation", purpose: "Catalog existing recordings, select usable cases, link ground-truth notes, and prepare validation datasets.", owner: "", status: "active" },
  { id: "WS-VALID", label: "Validation Science", purpose: "Quantify transcription accuracy, speaker attribution, variable extraction, PEPRisc agreement, latency, workflow feasibility, and safety.", owner: "", status: "active" },
  { id: "WS-IRB", label: "IRB / HIPAA / Hopkins IT", purpose: "Ensure data capture, storage, processing, compute, and access comply with IRB, HIPAA, and Hopkins IT requirements.", owner: "", status: "active" },
  { id: "WS-INFRA", label: "Secure Infrastructure", purpose: "Decide where ASR, diarization, structured extraction, and PEPRisc inference should run.", owner: "", status: "active" },
  { id: "WS-FDA", label: "FDA / Regulatory Strategy", purpose: "Define intended use, CDS/SaMD classification, non-device CDS criteria, pre-submission needs, and AI lifecycle planning.", owner: "", status: "active" },
  { id: "WS-TRANS", label: "Industry / Translation", purpose: "Prepare the project for JHTV, Olympus, licensing, and partnership discussions.", owner: "", status: "active" },
  { id: "WS-FUTURE", label: "Future Modules", purpose: "Track downstream concepts such as template-generating agents, video mapping, papilla morphology, and additional prediction models.", owner: "", status: "active" },
];

export const MOCK_TASKS: RoadmapTask[] = [
  {
    id: "CLIN-001", title: "Define prospective non-interventional shadow workflow",
    description: "Design the end-to-end workflow for running EndoScribe + PEPRisc in shadow mode during live ERCPs without affecting clinical decisions.",
    workstream_id: "WS-CLIN",
    owner: "Richu Ravikumar", contributors: ["PI"],
    status: "Not started" as const,
    priority: "Critical" as const,
    start_date: "2026-05-10", target_date: "2026-05-24",
    dependencies: ["IRB-001"], deliverables: ["Shadow workflow protocol document"],
    blockers: [], risks: ["Workflow may disrupt procedure flow"],
    decision_needed: "PI approval of shadow workflow design",
    regulatory_relevance: "Moderate" as const,
    hipaa_relevance: "High" as const,
    evidence_stage: "Concept" as const,
    gsd_goal: "Establish validated prospective shadow-mode pipeline", next_action: "Draft initial shadow workflow diagram", notes: "",
  },
  {
    id: "CLIN-002", title: "Decide PEPRisc output audience",
    description: "Determine whether PEPRisc output during shadow validation is research-only, coordinator-facing, or clinician-facing.",
    workstream_id: "WS-CLIN",
    owner: "PI", contributors: ["Richu Ravikumar"],
    status: "Not started" as const,
    priority: "Critical" as const,
    start_date: "2026-05-12", target_date: "2026-05-24",
    dependencies: ["CLIN-001", "FDA-001"], deliverables: ["Decision memo on PEPRisc output visibility"],
    blockers: [], risks: ["Clinician-facing use triggers higher regulatory requirements"],
    decision_needed: "Who sees PEPRisc output during shadow validation?",
    regulatory_relevance: "High" as const,
    hipaa_relevance: "Moderate" as const,
    evidence_stage: "Concept" as const,
    gsd_goal: "Establish validated prospective shadow-mode pipeline", next_action: "Schedule PI discussion on output audience", notes: "",
  },
  {
    id: "CLIN-003", title: "Draft ERCP dictation SOP",
    description: "Create a standard operating procedure for endoscopist dictation during ERCP to ensure consistent, structured speech capture.",
    workstream_id: "WS-CLIN",
    owner: "Richu Ravikumar", contributors: ["PI", "Endoscopists"],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-05-17", target_date: "2026-05-31",
    dependencies: [], deliverables: ["ERCP dictation SOP document"],
    blockers: [], risks: ["Endoscopist compliance with SOP may vary"],
    decision_needed: "",
    regulatory_relevance: "Low" as const,
    hipaa_relevance: "Low" as const,
    evidence_stage: "Concept" as const,
    gsd_goal: "Standardize procedural dictation for AI capture", next_action: "Review existing dictation patterns from recordings", notes: "",
  },
  {
    id: "CLIN-004", title: "Define team responsibilities",
    description: "Define roles and responsibilities for endoscopists, coordinators, interns, reviewers, Richu, PI, and technical collaborators.",
    workstream_id: "WS-CLIN",
    owner: "Richu Ravikumar", contributors: ["PI"],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-05-19", target_date: "2026-06-02",
    dependencies: ["CLIN-001"], deliverables: ["RACI matrix"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "None" as const,
    hipaa_relevance: "Low" as const,
    evidence_stage: "Concept" as const,
    gsd_goal: "Clear project accountability", next_action: "Draft RACI matrix", notes: "",
  },
  {
    id: "PLATFORM-001", title: "Create systems architecture diagram",
    description: "Design and document the full EndoScribe systems architecture including audio input, ASR, diarization, extraction, PEPRisc, storage, and output.",
    workstream_id: "WS-PLATFORM",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "Critical" as const,
    start_date: "2026-05-10", target_date: "2026-05-20",
    dependencies: [], deliverables: ["Systems architecture diagram"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "Low" as const,
    hipaa_relevance: "Moderate" as const,
    evidence_stage: "Concept" as const,
    gsd_goal: "Define EndoScribe platform architecture", next_action: "Draft architecture diagram", notes: "",
  },
  {
    id: "PLATFORM-002", title: "Create PHI-aware data-flow diagram",
    description: "Map all data flows with explicit PHI tagging at each node: where PHI enters, where it is processed, stored, and where it must not go.",
    workstream_id: "WS-PLATFORM",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "Critical" as const,
    start_date: "2026-05-14", target_date: "2026-05-24",
    dependencies: ["PLATFORM-001"], deliverables: ["PHI-aware data-flow diagram"],
    blockers: [], risks: ["Missed PHI touchpoints could cause compliance failure"],
    decision_needed: "",
    regulatory_relevance: "Moderate" as const,
    hipaa_relevance: "High" as const,
    evidence_stage: "Concept" as const,
    gsd_goal: "Define EndoScribe platform architecture", next_action: "Identify all data touchpoints", notes: "",
  },
  {
    id: "PLATFORM-003", title: "Define structured ERCP note schema",
    description: "Design the structured output schema for ERCP notes generated from transcription and variable extraction.",
    workstream_id: "WS-PLATFORM",
    owner: "Richu Ravikumar", contributors: ["PI"],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-06-01", target_date: "2026-06-14",
    dependencies: [], deliverables: ["ERCP note schema specification"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "Low" as const,
    hipaa_relevance: "Low" as const,
    evidence_stage: "Development" as const,
    gsd_goal: "Define EndoScribe platform architecture", next_action: "Review existing ERCP note templates", notes: "",
  },
  {
    id: "PLATFORM-004", title: "Define transcript-to-PEPRisc variable extraction pipeline",
    description: "Design the pipeline that extracts PEPRisc-relevant variables from structured transcripts.",
    workstream_id: "WS-PLATFORM",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-06-10", target_date: "2026-06-24",
    dependencies: ["PLATFORM-003", "PEP-001"], deliverables: ["Variable extraction pipeline design document"],
    blockers: [], risks: ["Extraction accuracy may be insufficient for reliable risk scoring"],
    decision_needed: "",
    regulatory_relevance: "Moderate" as const,
    hipaa_relevance: "Moderate" as const,
    evidence_stage: "Development" as const,
    gsd_goal: "Integrate PEPRisc into EndoScribe pipeline", next_action: "Map PEPRisc variables to dictation phrases", notes: "",
  },
  {
    id: "PLATFORM-005", title: "Define audit logging and output capture requirements",
    description: "Specify what must be logged for audit trail: inputs, outputs, model versions, timestamps, user actions, and error states.",
    workstream_id: "WS-PLATFORM",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-06-08", target_date: "2026-06-22",
    dependencies: ["PLATFORM-001"], deliverables: ["Audit logging requirements specification"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "High" as const,
    hipaa_relevance: "High" as const,
    evidence_stage: "Development" as const,
    gsd_goal: "Ensure regulatory and compliance readiness", next_action: "Draft logging requirements", notes: "",
  },
  {
    id: "PEP-001", title: "Freeze current PEPRisc variable schema",
    description: "Lock the current set of PEPRisc input variables for shadow-mode validation.",
    workstream_id: "WS-PEP",
    owner: "Richu Ravikumar", contributors: ["PI"],
    status: "Not started" as const,
    priority: "Critical" as const,
    start_date: "2026-06-01", target_date: "2026-06-10",
    dependencies: [], deliverables: ["Frozen PEPRisc variable schema document"],
    blockers: [], risks: [],
    decision_needed: "PI sign-off on variable freeze",
    regulatory_relevance: "Moderate" as const,
    hipaa_relevance: "None" as const,
    evidence_stage: "Development" as const,
    gsd_goal: "Integrate PEPRisc into EndoScribe pipeline", next_action: "Document current PEPRisc variable list", notes: "",
  },
  {
    id: "PEP-002", title: "Map dictated ERCP phrases to PEPRisc variables",
    description: "Create a mapping between natural-language dictation phrases and the structured PEPRisc input variables.",
    workstream_id: "WS-PEP",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-06-07", target_date: "2026-06-18",
    dependencies: ["PEP-001"], deliverables: ["Phrase-to-variable mapping table"],
    blockers: [], risks: ["Ambiguous dictation may not map cleanly"],
    decision_needed: "",
    regulatory_relevance: "Moderate" as const,
    hipaa_relevance: "None" as const,
    evidence_stage: "Development" as const,
    gsd_goal: "Integrate PEPRisc into EndoScribe pipeline", next_action: "Review sample transcripts for variable mentions", notes: "",
  },
  {
    id: "PEP-003", title: "Build shadow-mode inference pipeline",
    description: "Implement PEPRisc inference that runs in shadow mode alongside ERCP procedures without clinical output.",
    workstream_id: "WS-PEP",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-06-14", target_date: "2026-06-28",
    dependencies: ["PEP-001", "PLATFORM-004", "INFRA-002"], deliverables: ["Working shadow-mode PEPRisc pipeline"],
    blockers: [], risks: ["Latency may exceed acceptable threshold"],
    decision_needed: "",
    regulatory_relevance: "Moderate" as const,
    hipaa_relevance: "High" as const,
    evidence_stage: "Development" as const,
    gsd_goal: "Integrate PEPRisc into EndoScribe pipeline", next_action: "Design inference pipeline architecture", notes: "",
  },
  {
    id: "PEP-004", title: "Compare EndoScribe-derived PEPRisc output against ground truth",
    description: "Validate EndoScribe-extracted PEPRisc scores against manually abstracted ground-truth PEPRisc scores.",
    workstream_id: "WS-PEP",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-06-21", target_date: "2026-06-30",
    dependencies: ["PEP-003", "DATA-002"], deliverables: ["Agreement analysis report"],
    blockers: [], risks: ["Insufficient sample size for robust comparison"],
    decision_needed: "",
    regulatory_relevance: "High" as const,
    hipaa_relevance: "Moderate" as const,
    evidence_stage: "Internal validation" as const,
    gsd_goal: "Validate PEPRisc integration accuracy", next_action: "Define comparison methodology", notes: "",
  },
  {
    id: "PEP-005", title: "Determine whether PEPRisc model requires updating",
    description: "Assess whether the current PEPRisc model should be retrained or updated with newer data before prospective validation.",
    workstream_id: "WS-PEP",
    owner: "Richu Ravikumar", contributors: ["PI"],
    status: "Not started" as const,
    priority: "Medium" as const,
    start_date: "2026-06-07", target_date: "2026-06-21",
    dependencies: ["PEP-001"], deliverables: ["Model update assessment memo"],
    blockers: [], risks: ["Model update could delay timeline"],
    decision_needed: "PI decision on model update strategy",
    regulatory_relevance: "High" as const,
    hipaa_relevance: "None" as const,
    evidence_stage: "Development" as const,
    gsd_goal: "Ensure PEPRisc model is validation-ready", next_action: "Review model performance on recent data", notes: "",
  },
  {
    id: "AUDIO-001", title: "Design phone vs OR-level microphone experiment",
    description: "Design a controlled experiment comparing phone microphones and OR-level microphones for endoscopy-suite dictation capture.",
    workstream_id: "WS-AUDIO",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-05-17", target_date: "2026-05-30",
    dependencies: [], deliverables: ["Microphone comparison experiment protocol"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "None" as const,
    hipaa_relevance: "Moderate" as const,
    evidence_stage: "Concept" as const,
    gsd_goal: "Determine optimal audio capture for EndoScribe", next_action: "Research OR-level microphone options", notes: "",
  },
  {
    id: "AUDIO-002", title: "Identify OR-level microphone option",
    description: "Research and select a high-quality OR-level microphone suitable for endoscopy suite use.",
    workstream_id: "WS-AUDIO",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "Medium" as const,
    start_date: "2026-05-17", target_date: "2026-05-30",
    dependencies: [], deliverables: ["Microphone recommendation memo"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "None" as const,
    hipaa_relevance: "None" as const,
    evidence_stage: "Concept" as const,
    gsd_goal: "Determine optimal audio capture for EndoScribe", next_action: "Survey available OR-grade microphones", notes: "",
  },
  {
    id: "AUDIO-003", title: "Run simulated dictation test",
    description: "Test microphone options under simulated procedure-room conditions with controlled background noise levels.",
    workstream_id: "WS-AUDIO",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "Medium" as const,
    start_date: "2026-05-31", target_date: "2026-06-14",
    dependencies: ["AUDIO-001", "AUDIO-002"], deliverables: ["Simulated test results report"],
    blockers: [], risks: ["Simulated conditions may not match real OR environment"],
    decision_needed: "",
    regulatory_relevance: "None" as const,
    hipaa_relevance: "None" as const,
    evidence_stage: "Internal validation" as const,
    gsd_goal: "Validate audio capture quality", next_action: "Set up simulated test environment", notes: "",
  },
  {
    id: "AUDIO-004", title: "Run live-suite feasibility testing",
    description: "Test audio capture in a live endoscopy suite. This must only proceed under an IRB-approved workflow.",
    workstream_id: "WS-AUDIO",
    owner: "Richu Ravikumar", contributors: ["PI"],
    status: "Not started" as const,
    priority: "Medium" as const,
    start_date: "2026-06-07", target_date: "2026-06-21",
    dependencies: ["AUDIO-003", "IRB-001"], deliverables: ["Live-suite audio feasibility report"],
    blockers: ["Requires IRB approval"], risks: ["IRB approval timeline"],
    decision_needed: "",
    regulatory_relevance: "Low" as const,
    hipaa_relevance: "High" as const,
    evidence_stage: "Prospective validation" as const,
    gsd_goal: "Validate audio capture quality", next_action: "Await IRB status", notes: "Do not proceed without IRB approval.",
  },
  {
    id: "ASR-001", title: "Compare Whisper vs Med-ASR-type models",
    description: "Benchmark Whisper against medical ASR systems on ERCP dictation audio.",
    workstream_id: "WS-ASR",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-05-24", target_date: "2026-06-07",
    dependencies: ["DATA-002"], deliverables: ["ASR comparison report"],
    blockers: [], risks: ["Medical terminology accuracy may be low for general models"],
    decision_needed: "",
    regulatory_relevance: "Low" as const,
    hipaa_relevance: "Moderate" as const,
    evidence_stage: "Development" as const,
    gsd_goal: "Select best ASR system for EndoScribe", next_action: "Set up Whisper evaluation environment", notes: "",
  },
  {
    id: "ASR-002", title: "Evaluate WER, CER, terminology error rate, and latency",
    description: "Compute word error rate, character error rate, medical terminology error rate, and processing latency for candidate ASR systems.",
    workstream_id: "WS-ASR",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-05-26", target_date: "2026-06-07",
    dependencies: ["ASR-001"], deliverables: ["ASR metrics report"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "Low" as const,
    hipaa_relevance: "Low" as const,
    evidence_stage: "Internal validation" as const,
    gsd_goal: "Quantify ASR performance", next_action: "Define evaluation script and test set", notes: "",
  },
  {
    id: "ASR-003", title: "Determine HIPAA-compliant hosting options",
    description: "Evaluate hosting options for ASR inference that comply with HIPAA and Hopkins IT requirements.",
    workstream_id: "WS-ASR",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-05-26", target_date: "2026-06-10",
    dependencies: [], deliverables: ["HIPAA-compliant ASR hosting assessment"],
    blockers: [], risks: ["Cloud ASR may require BAA"],
    decision_needed: "Hopkins IT input on approved hosting",
    regulatory_relevance: "Moderate" as const,
    hipaa_relevance: "High" as const,
    evidence_stage: "Development" as const,
    gsd_goal: "Ensure HIPAA-compliant ASR deployment", next_action: "Research Hopkins-approved compute options", notes: "",
  },
  {
    id: "ASR-004", title: "Assess feasibility of GI/ERCP-specific fine-tuning",
    description: "Determine whether fine-tuning ASR on GI/ERCP-specific terminology is feasible, beneficial, and compliant.",
    workstream_id: "WS-ASR",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "Medium" as const,
    start_date: "2026-06-07", target_date: "2026-06-21",
    dependencies: ["ASR-001", "ASR-002"], deliverables: ["Fine-tuning feasibility assessment"],
    blockers: [], risks: ["Insufficient training data for fine-tuning"],
    decision_needed: "",
    regulatory_relevance: "Low" as const,
    hipaa_relevance: "Moderate" as const,
    evidence_stage: "Development" as const,
    gsd_goal: "Optimize ASR for ERCP", next_action: "Estimate available training data volume", notes: "",
  },
  {
    id: "DIAR-001", title: "Define multi-speaker endoscopy-room problem",
    description: "Document the multi-speaker challenge in endoscopy rooms: staff roles, cross-talk patterns, background noise, and speaker isolation requirements.",
    workstream_id: "WS-DIAR",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-05-19", target_date: "2026-06-02",
    dependencies: [], deliverables: ["Multi-speaker problem specification"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "None" as const,
    hipaa_relevance: "Low" as const,
    evidence_stage: "Concept" as const,
    gsd_goal: "Enable primary-speaker isolation for EndoScribe", next_action: "Review existing recordings for speaker patterns", notes: "",
  },
  {
    id: "DIAR-002", title: "Prototype primary endoscopist speaker detection",
    description: "Build a prototype to detect and isolate the primary endoscopist's voice from multi-speaker procedure audio.",
    workstream_id: "WS-DIAR",
    owner: "TBD", contributors: ["Richu Ravikumar"],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-06-02", target_date: "2026-06-18",
    dependencies: ["DIAR-001", "DATA-002"], deliverables: ["Diarization prototype"],
    blockers: [], risks: ["Cross-talk may defeat simple diarization"],
    decision_needed: "",
    regulatory_relevance: "None" as const,
    hipaa_relevance: "Moderate" as const,
    evidence_stage: "Development" as const,
    gsd_goal: "Enable primary-speaker isolation for EndoScribe", next_action: "Evaluate diarization libraries and approaches", notes: "",
  },
  {
    id: "DIAR-003", title: "Evaluate speaker attribution accuracy",
    description: "Measure diarization accuracy for attributing speech to the correct speaker.",
    workstream_id: "WS-DIAR",
    owner: "TBD", contributors: ["Richu Ravikumar"],
    status: "Not started" as const,
    priority: "Medium" as const,
    start_date: "2026-06-09", target_date: "2026-06-21",
    dependencies: ["DIAR-002"], deliverables: ["Speaker attribution accuracy report"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "None" as const,
    hipaa_relevance: "Low" as const,
    evidence_stage: "Internal validation" as const,
    gsd_goal: "Validate diarization quality", next_action: "Define attribution accuracy metrics", notes: "",
  },
  {
    id: "DIAR-004", title: "Decide intern ownership of diarization workstream",
    description: "Determine whether the intern with CLSP/audio background can own the diarization workstream.",
    workstream_id: "WS-DIAR",
    owner: "Richu Ravikumar", contributors: ["PI"],
    status: "Not started" as const,
    priority: "Medium" as const,
    start_date: "2026-05-24", target_date: "2026-06-02",
    dependencies: [], deliverables: ["Ownership decision"],
    blockers: [], risks: [],
    decision_needed: "Can intern with CLSP background own diarization?",
    regulatory_relevance: "None" as const,
    hipaa_relevance: "None" as const,
    evidence_stage: "Concept" as const,
    gsd_goal: "Assign workstream ownership", next_action: "Discuss with PI and intern", notes: "",
  },
  {
    id: "DATA-001", title: "Complete catalog of existing recordings",
    description: "Catalog all 35-40 existing recordings with metadata: procedure type, recording quality, completeness, date, and linked notes.",
    workstream_id: "WS-DATA",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "Critical" as const,
    start_date: "2026-05-10", target_date: "2026-05-21",
    dependencies: [], deliverables: ["Recording catalog spreadsheet"],
    blockers: [], risks: ["Some recordings may be unusable"],
    decision_needed: "",
    regulatory_relevance: "None" as const,
    hipaa_relevance: "High" as const,
    evidence_stage: "Development" as const,
    gsd_goal: "Curate validation dataset", next_action: "List all available recordings", notes: "PHI must remain in Hopkins-approved environment.",
  },
  {
    id: "DATA-002", title: "Select 10 highest-quality recordings",
    description: "Select approximately 10 recordings with highest audio quality, completeness, and ground-truth linkage for initial testing.",
    workstream_id: "WS-DATA",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-05-15", target_date: "2026-05-24",
    dependencies: ["DATA-001"], deliverables: ["Curated test set of 10 recordings"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "None" as const,
    hipaa_relevance: "High" as const,
    evidence_stage: "Development" as const,
    gsd_goal: "Curate validation dataset", next_action: "Review catalog for quality rankings", notes: "",
  },
  {
    id: "DATA-003", title: "Link recordings to procedure type, notes, and PEPRisc ground truth",
    description: "For each curated recording, link to procedure type, final procedure note, and manually abstracted PEPRisc variable ground truth.",
    workstream_id: "WS-DATA",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-05-24", target_date: "2026-06-07",
    dependencies: ["DATA-002"], deliverables: ["Linked recording-note-variable dataset"],
    blockers: [], risks: ["Ground-truth abstraction is labor-intensive"],
    decision_needed: "",
    regulatory_relevance: "None" as const,
    hipaa_relevance: "High" as const,
    evidence_stage: "Development" as const,
    gsd_goal: "Curate validation dataset", next_action: "Begin ground-truth abstraction", notes: "",
  },
  {
    id: "DATA-004", title: "Label recording completeness and quality",
    description: "Apply quality and completeness labels to all cataloged recordings.",
    workstream_id: "WS-DATA",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "Medium" as const,
    start_date: "2026-05-19", target_date: "2026-06-02",
    dependencies: ["DATA-001"], deliverables: ["Quality-labeled recording catalog"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "None" as const,
    hipaa_relevance: "Moderate" as const,
    evidence_stage: "Development" as const,
    gsd_goal: "Curate validation dataset", next_action: "Define quality labeling criteria", notes: "",
  },
  {
    id: "DATA-005", title: "Create de-identified metadata table",
    description: "Create a de-identified metadata table for recordings that can be used outside Hopkins-approved environments for planning purposes.",
    workstream_id: "WS-DATA",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "Medium" as const,
    start_date: "2026-05-21", target_date: "2026-06-04",
    dependencies: ["DATA-001"], deliverables: ["De-identified metadata table"],
    blockers: [], risks: ["Re-identification risk must be assessed"],
    decision_needed: "",
    regulatory_relevance: "None" as const,
    hipaa_relevance: "High" as const,
    evidence_stage: "Development" as const,
    gsd_goal: "Enable safe data sharing for planning", next_action: "Define de-identification requirements", notes: "",
  },
  {
    id: "DATA-006", title: "Resolve backlog of unedited/incomplete recordings",
    description: "Review and resolve recordings that are unedited, incomplete, or missing metadata.",
    workstream_id: "WS-DATA",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "Medium" as const,
    start_date: "2026-05-19", target_date: "2026-06-04",
    dependencies: ["DATA-001"], deliverables: ["Resolved recording backlog"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "None" as const,
    hipaa_relevance: "Moderate" as const,
    evidence_stage: "Development" as const,
    gsd_goal: "Curate validation dataset", next_action: "Identify incomplete recordings from catalog", notes: "",
  },
  {
    id: "VALID-001", title: "Define ASR validation metrics",
    description: "Specify metrics for evaluating ASR performance: WER, CER, medical terminology error rate, latency, failure rate.",
    workstream_id: "WS-VALID",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-06-01", target_date: "2026-06-12",
    dependencies: [], deliverables: ["ASR validation metrics specification"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "Low" as const,
    hipaa_relevance: "None" as const,
    evidence_stage: "Concept" as const,
    gsd_goal: "Establish rigorous validation framework", next_action: "Draft metrics specification", notes: "",
  },
  {
    id: "VALID-002", title: "Define diarization validation metrics",
    description: "Specify metrics for evaluating speaker diarization: primary speaker identification accuracy, cross-talk handling, attribution accuracy.",
    workstream_id: "WS-VALID",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-06-03", target_date: "2026-06-14",
    dependencies: [], deliverables: ["Diarization validation metrics specification"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "None" as const,
    hipaa_relevance: "None" as const,
    evidence_stage: "Concept" as const,
    gsd_goal: "Establish rigorous validation framework", next_action: "Draft metrics specification", notes: "",
  },
  {
    id: "VALID-003", title: "Define variable-extraction validation metrics",
    description: "Specify metrics for variable extraction: sensitivity, specificity, PPV, NPV, F1, Cohen's kappa, missing-variable rate.",
    workstream_id: "WS-VALID",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-06-05", target_date: "2026-06-16",
    dependencies: [], deliverables: ["Variable extraction metrics specification"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "Moderate" as const,
    hipaa_relevance: "None" as const,
    evidence_stage: "Concept" as const,
    gsd_goal: "Establish rigorous validation framework", next_action: "Draft metrics specification", notes: "",
  },
  {
    id: "VALID-004", title: "Define PEPRisc risk-output agreement metrics",
    description: "Specify metrics for PEPRisc output validation: agreement with manual abstraction, Bland-Altman, calibration, AUC/ROC, DeLong comparison.",
    workstream_id: "WS-VALID",
    owner: "Richu Ravikumar", contributors: ["PI"],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-06-08", target_date: "2026-06-20",
    dependencies: ["PEP-001"], deliverables: ["PEPRisc agreement metrics specification"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "High" as const,
    hipaa_relevance: "None" as const,
    evidence_stage: "Concept" as const,
    gsd_goal: "Establish rigorous validation framework", next_action: "Draft metrics specification", notes: "",
  },
  {
    id: "VALID-005", title: "Define workflow feasibility metrics",
    description: "Specify metrics for workflow feasibility: case completion rate, time to output, manual corrections, coordinator/endoscopist burden, failure modes.",
    workstream_id: "WS-VALID",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "Medium" as const,
    start_date: "2026-06-10", target_date: "2026-06-22",
    dependencies: [], deliverables: ["Workflow feasibility metrics specification"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "Low" as const,
    hipaa_relevance: "None" as const,
    evidence_stage: "Concept" as const,
    gsd_goal: "Establish rigorous validation framework", next_action: "Draft metrics specification", notes: "",
  },
  {
    id: "VALID-006", title: "Build failure-mode and clinically material error taxonomy",
    description: "Create a taxonomy of failure modes and clinically material errors across all pipeline components.",
    workstream_id: "WS-VALID",
    owner: "Richu Ravikumar", contributors: ["PI"],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-06-14", target_date: "2026-06-30",
    dependencies: [], deliverables: ["Failure-mode taxonomy"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "High" as const,
    hipaa_relevance: "None" as const,
    evidence_stage: "Concept" as const,
    gsd_goal: "Establish rigorous validation framework", next_action: "Review literature on AI clinical error taxonomies", notes: "",
  },
  {
    id: "IRB-001", title: "Determine whether IRB amendment is required",
    description: "Assess whether current IRB approval covers audio capture, AI transcription, variable extraction, and risk-score generation, or whether an amendment is needed.",
    workstream_id: "WS-IRB",
    owner: "Richu Ravikumar", contributors: ["PI"],
    status: "Not started" as const,
    priority: "Critical" as const,
    start_date: "2026-05-10", target_date: "2026-05-22",
    dependencies: [], deliverables: ["IRB amendment assessment"],
    blockers: [], risks: ["Amendment process may delay timeline"],
    decision_needed: "Does current IRB cover planned activities?",
    regulatory_relevance: "High" as const,
    hipaa_relevance: "High" as const,
    evidence_stage: "Regulatory planning" as const,
    gsd_goal: "Ensure regulatory compliance", next_action: "Review current IRB protocol", notes: "",
  },
  {
    id: "IRB-002", title: "Draft IRB amendment language",
    description: "Draft amendment language covering audio capture, AI transcription, variable extraction, and risk-score generation.",
    workstream_id: "WS-IRB",
    owner: "Richu Ravikumar", contributors: ["PI"],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-06-01", target_date: "2026-06-21",
    dependencies: ["IRB-001"], deliverables: ["Draft IRB amendment"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "High" as const,
    hipaa_relevance: "High" as const,
    evidence_stage: "Regulatory planning" as const,
    gsd_goal: "Ensure regulatory compliance", next_action: "Await IRB-001 assessment", notes: "",
  },
  {
    id: "IRB-003", title: "Confirm all team members listed on IRB",
    description: "Verify that all team members with data access are listed on the IRB protocol.",
    workstream_id: "WS-IRB",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-06-01", target_date: "2026-06-10",
    dependencies: [], deliverables: ["Team-IRB coverage confirmation"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "High" as const,
    hipaa_relevance: "High" as const,
    evidence_stage: "Regulatory planning" as const,
    gsd_goal: "Ensure regulatory compliance", next_action: "Review IRB personnel list", notes: "",
  },
  {
    id: "IRB-004", title: "Define approved storage location",
    description: "Identify and confirm Hopkins-approved storage locations for all PHI, audio, transcripts, and derived data.",
    workstream_id: "WS-IRB",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "Critical" as const,
    start_date: "2026-06-05", target_date: "2026-06-25",
    dependencies: [], deliverables: ["Approved storage location specification"],
    blockers: [], risks: [],
    decision_needed: "Hopkins IT confirmation of approved storage",
    regulatory_relevance: "High" as const,
    hipaa_relevance: "High" as const,
    evidence_stage: "Regulatory planning" as const,
    gsd_goal: "Ensure data governance compliance", next_action: "Contact Hopkins IT", notes: "",
  },
  {
    id: "IRB-005", title: "Define PHI boundary rule",
    description: "Formally document the rule that PHI cannot leave Hopkins-approved environments without explicit institutional approval.",
    workstream_id: "WS-IRB",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "Critical" as const,
    start_date: "2026-06-01", target_date: "2026-06-15",
    dependencies: [], deliverables: ["PHI boundary rule document"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "High" as const,
    hipaa_relevance: "High" as const,
    evidence_stage: "Regulatory planning" as const,
    gsd_goal: "Ensure data governance compliance", next_action: "Draft PHI boundary rule", notes: "",
  },
  {
    id: "IRB-006", title: "Determine consent language for AI transcription/risk scoring",
    description: "Assess whether existing consent language adequately covers AI transcription and risk-score generation, or whether updates are needed.",
    workstream_id: "WS-IRB",
    owner: "Richu Ravikumar", contributors: ["PI"],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-06-10", target_date: "2026-06-30",
    dependencies: ["IRB-001"], deliverables: ["Consent language assessment"],
    blockers: [], risks: [],
    decision_needed: "Does consent need AI-specific language?",
    regulatory_relevance: "High" as const,
    hipaa_relevance: "High" as const,
    evidence_stage: "Regulatory planning" as const,
    gsd_goal: "Ensure regulatory compliance", next_action: "Review current consent form", notes: "",
  },
  {
    id: "INFRA-001", title: "Compare compute options",
    description: "Compare local GPU tower, JHU Discovery, Hopkins-managed server, and secure cloud options for ASR and PEPRisc inference.",
    workstream_id: "WS-INFRA",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-05-24", target_date: "2026-06-07",
    dependencies: [], deliverables: ["Compute options comparison table"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "Moderate" as const,
    hipaa_relevance: "High" as const,
    evidence_stage: "Development" as const,
    gsd_goal: "Select HIPAA-compliant compute infrastructure", next_action: "Research available options", notes: "",
  },
  {
    id: "INFRA-002", title: "Decide where ASR and PEPRisc inference will run",
    description: "Make a decision on the compute environment for shadow-mode validation.",
    workstream_id: "WS-INFRA",
    owner: "Richu Ravikumar", contributors: ["PI"],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-06-02", target_date: "2026-06-16",
    dependencies: ["INFRA-001", "IRB-004"], deliverables: ["Compute environment decision memo"],
    blockers: [], risks: ["Compute costs may exceed budget"],
    decision_needed: "PI/IT approval of compute environment",
    regulatory_relevance: "Moderate" as const,
    hipaa_relevance: "High" as const,
    evidence_stage: "Development" as const,
    gsd_goal: "Select HIPAA-compliant compute infrastructure", next_action: "Present options to PI", notes: "",
  },
  {
    id: "INFRA-003", title: "Define access-control requirements",
    description: "Specify who can access what data, systems, and compute resources.",
    workstream_id: "WS-INFRA",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-05-26", target_date: "2026-06-10",
    dependencies: [], deliverables: ["Access-control requirements document"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "Moderate" as const,
    hipaa_relevance: "High" as const,
    evidence_stage: "Development" as const,
    gsd_goal: "Ensure secure infrastructure", next_action: "Draft access-control matrix", notes: "",
  },
  {
    id: "INFRA-004", title: "Define audit-trail requirements",
    description: "Specify audit-trail requirements for all system access and data processing.",
    workstream_id: "WS-INFRA",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "Medium" as const,
    start_date: "2026-05-28", target_date: "2026-06-14",
    dependencies: [], deliverables: ["Audit-trail requirements document"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "High" as const,
    hipaa_relevance: "High" as const,
    evidence_stage: "Development" as const,
    gsd_goal: "Ensure secure infrastructure", next_action: "Draft audit-trail specification", notes: "",
  },
  {
    id: "INFRA-005", title: "Define future edge-device assumptions",
    description: "Document assumptions about future edge-device deployment for industry integration scenarios.",
    workstream_id: "WS-INFRA",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "Low" as const,
    start_date: "2026-07-01", target_date: "2026-08-01",
    dependencies: [], deliverables: ["Edge-device assumptions document"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "Moderate" as const,
    hipaa_relevance: "Moderate" as const,
    evidence_stage: "Future module" as const,
    gsd_goal: "Plan for industry-scale deployment", next_action: "Research edge inference options", notes: "",
  },
  {
    id: "FDA-001", title: "Draft intended-use statement for EndoScribe documentation",
    description: "Write an intended-use statement for EndoScribe's documentation function (transcription and structured note generation with human review).",
    workstream_id: "WS-FDA",
    owner: "Richu Ravikumar", contributors: ["PI"],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-05-12", target_date: "2026-05-23",
    dependencies: [], deliverables: ["EndoScribe intended-use statement"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "High" as const,
    hipaa_relevance: "None" as const,
    evidence_stage: "Regulatory planning" as const,
    gsd_goal: "Establish regulatory strategy", next_action: "Draft intended-use statement", notes: "",
  },
  {
    id: "FDA-002", title: "Draft intended-use statement for PEPRisc shadow mode",
    description: "Write an intended-use statement for PEPRisc operating in non-interventional shadow mode during ERCP.",
    workstream_id: "WS-FDA",
    owner: "Richu Ravikumar", contributors: ["PI"],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-05-14", target_date: "2026-05-24",
    dependencies: ["CLIN-002"], deliverables: ["PEPRisc shadow-mode intended-use statement"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "High" as const,
    hipaa_relevance: "None" as const,
    evidence_stage: "Regulatory planning" as const,
    gsd_goal: "Establish regulatory strategy", next_action: "Draft intended-use statement", notes: "",
  },
  {
    id: "FDA-003", title: "Assess FDA non-device CDS criteria",
    description: "Evaluate whether EndoScribe and PEPRisc meet FDA's non-device CDS (Clinical Decision Support) criteria under 21st Century Cures Act.",
    workstream_id: "WS-FDA",
    owner: "Richu Ravikumar", contributors: ["PI"],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-06-15", target_date: "2026-07-05",
    dependencies: ["FDA-001", "FDA-002"], deliverables: ["CDS criteria assessment"],
    blockers: [], risks: ["Misclassification could have regulatory consequences"],
    decision_needed: "",
    regulatory_relevance: "High" as const,
    hipaa_relevance: "None" as const,
    evidence_stage: "Regulatory planning" as const,
    gsd_goal: "Establish regulatory strategy", next_action: "Review FDA CDS guidance documents", notes: "",
  },
  {
    id: "FDA-004", title: "Separate platform functions from clinical prediction modules",
    description: "Distinguish EndoScribe platform functions (transcription, documentation) from clinical prediction modules (PEPRisc) for regulatory classification.",
    workstream_id: "WS-FDA",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "High" as const,
    start_date: "2026-06-01", target_date: "2026-06-20",
    dependencies: [], deliverables: ["Platform vs prediction module classification document"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "High" as const,
    hipaa_relevance: "None" as const,
    evidence_stage: "Regulatory planning" as const,
    gsd_goal: "Establish regulatory strategy", next_action: "Draft classification framework", notes: "",
  },
  {
    id: "FDA-005", title: "Create regulatory risk tier table",
    description: "Build a table mapping system functions to regulatory risk tiers from documentation-only through real-time procedural recommendation.",
    workstream_id: "WS-FDA",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "Medium" as const,
    start_date: "2026-06-15", target_date: "2026-07-05",
    dependencies: ["FDA-004"], deliverables: ["Regulatory risk tier table"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "High" as const,
    hipaa_relevance: "None" as const,
    evidence_stage: "Regulatory planning" as const,
    gsd_goal: "Establish regulatory strategy", next_action: "Draft tier table", notes: "",
  },
  {
    id: "FDA-006", title: "Draft FDA pre-submission question list",
    description: "Prepare a list of questions for a potential future FDA pre-submission meeting.",
    workstream_id: "WS-FDA",
    owner: "Richu Ravikumar", contributors: ["PI"],
    status: "Not started" as const,
    priority: "Medium" as const,
    start_date: "2026-06-20", target_date: "2026-07-10",
    dependencies: ["FDA-003"], deliverables: ["Pre-submission question list"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "High" as const,
    hipaa_relevance: "None" as const,
    evidence_stage: "Regulatory planning" as const,
    gsd_goal: "Establish regulatory strategy", next_action: "Draft question list", notes: "",
  },
  {
    id: "FDA-007", title: "Track AI lifecycle and predetermined change-control",
    description: "Document AI lifecycle considerations and predetermined change-control plan requirements for models that may be updated over time.",
    workstream_id: "WS-FDA",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "Medium" as const,
    start_date: "2026-06-15", target_date: "2026-07-15",
    dependencies: [], deliverables: ["AI lifecycle and change-control planning document"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "High" as const,
    hipaa_relevance: "None" as const,
    evidence_stage: "Regulatory planning" as const,
    gsd_goal: "Establish regulatory strategy", next_action: "Review FDA AI/ML lifecycle guidance", notes: "",
  },
  {
    id: "TRANS-001", title: "Create JHTV/Olympus-facing value proposition",
    description: "Develop a value proposition document for JHTV and Olympus partnership discussions.",
    workstream_id: "WS-TRANS",
    owner: "Richu Ravikumar", contributors: ["PI"],
    status: "Not started" as const,
    priority: "Medium" as const,
    start_date: "2026-06-15", target_date: "2026-07-10",
    dependencies: [], deliverables: ["Value proposition document"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "None" as const,
    hipaa_relevance: "None" as const,
    evidence_stage: "Translation" as const,
    gsd_goal: "Prepare translational pathway", next_action: "Draft value proposition", notes: "",
  },
  {
    id: "TRANS-002", title: "Define platform maturity ladder",
    description: "Define the maturity ladder from transcription to structured documentation to prediction to procedural AI co-pilot.",
    workstream_id: "WS-TRANS",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "Medium" as const,
    start_date: "2026-06-20", target_date: "2026-07-15",
    dependencies: [], deliverables: ["Platform maturity ladder document"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "None" as const,
    hipaa_relevance: "None" as const,
    evidence_stage: "Translation" as const,
    gsd_goal: "Prepare translational pathway", next_action: "Draft maturity ladder", notes: "",
  },
  {
    id: "TRANS-003", title: "Identify evidence package for licensing/partnership",
    description: "Define what evidence package would be needed for licensing or partnership discussions.",
    workstream_id: "WS-TRANS",
    owner: "Richu Ravikumar", contributors: ["PI"],
    status: "Not started" as const,
    priority: "Low" as const,
    start_date: "2026-07-01", target_date: "2026-07-31",
    dependencies: [], deliverables: ["Evidence package requirements"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "Moderate" as const,
    hipaa_relevance: "None" as const,
    evidence_stage: "Translation" as const,
    gsd_goal: "Prepare translational pathway", next_action: "Research typical evidence requirements", notes: "",
  },
  {
    id: "TRANS-004", title: "Prepare stakeholder map",
    description: "Map all stakeholders: internal (PI, lab, Hopkins IT, IRB, JHTV) and external (Olympus, industry partners, regulatory consultants).",
    workstream_id: "WS-TRANS",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "Medium" as const,
    start_date: "2026-06-25", target_date: "2026-07-15",
    dependencies: [], deliverables: ["Stakeholder map"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "None" as const,
    hipaa_relevance: "None" as const,
    evidence_stage: "Translation" as const,
    gsd_goal: "Prepare translational pathway", next_action: "Draft stakeholder map", notes: "",
  },
  {
    id: "FUTURE-001", title: "Define template-generating agent concept",
    description: "Conceptualize an agent that generates procedure-specific documentation templates from historical notes and institutional preferences.",
    workstream_id: "WS-FUTURE",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "Low" as const,
    start_date: "2026-07-01", target_date: "2026-07-31",
    dependencies: [], deliverables: ["Template agent concept document"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "Low" as const,
    hipaa_relevance: "Moderate" as const,
    evidence_stage: "Future module" as const,
    gsd_goal: "Expand EndoScribe platform capabilities", next_action: "Draft concept document", notes: "",
  },
  {
    id: "FUTURE-002", title: "Define video mapping / papilla morphology concept",
    description: "Conceptualize video-based analysis for papilla morphology classification and procedural mapping.",
    workstream_id: "WS-FUTURE",
    owner: "Richu Ravikumar", contributors: [],
    status: "Not started" as const,
    priority: "Low" as const,
    start_date: "2026-07-01", target_date: "2026-08-01",
    dependencies: [], deliverables: ["Video/papilla morphology concept document"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "Moderate" as const,
    hipaa_relevance: "Moderate" as const,
    evidence_stage: "Future module" as const,
    gsd_goal: "Expand EndoScribe platform capabilities", next_action: "Survey relevant literature", notes: "",
  },
  {
    id: "FUTURE-003", title: "Identify future prediction models",
    description: "Identify additional prediction models that could plug into EndoScribe: difficult cannulation, Barrett's, adverse events, etc.",
    workstream_id: "WS-FUTURE",
    owner: "Richu Ravikumar", contributors: ["PI"],
    status: "Not started" as const,
    priority: "Low" as const,
    start_date: "2026-07-15", target_date: "2026-08-15",
    dependencies: [], deliverables: ["Future prediction model inventory"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "Moderate" as const,
    hipaa_relevance: "None" as const,
    evidence_stage: "Future module" as const,
    gsd_goal: "Expand EndoScribe platform capabilities", next_action: "Survey GI prediction model literature", notes: "",
  },
  {
    id: "FUTURE-004", title: "Define long-term multicenter validation path",
    description: "Outline the pathway from single-center validation to multicenter validation studies.",
    workstream_id: "WS-FUTURE",
    owner: "Richu Ravikumar", contributors: ["PI"],
    status: "Not started" as const,
    priority: "Low" as const,
    start_date: "2026-07-15", target_date: "2026-08-15",
    dependencies: [], deliverables: ["Multicenter validation pathway document"],
    blockers: [], risks: [],
    decision_needed: "",
    regulatory_relevance: "High" as const,
    hipaa_relevance: "Moderate" as const,
    evidence_stage: "Future module" as const,
    gsd_goal: "Plan for scalable validation", next_action: "Draft multicenter pathway", notes: "",
  },
];

export const MOCK_MILESTONES: Milestone[] = [
  { id: "M1", title: "Foundation Complete", description: "Architecture, schemas, IRB assessment, and data catalog done", target_date: "2026-05-24", status: "Not started", workstream_id: null },
  { id: "M2", title: "Internal Validation Ready", description: "ASR evaluated, diarization prototyped, extraction pipeline built, 10-case test set ready", target_date: "2026-06-14", status: "Not started", workstream_id: null },
  { id: "M3", title: "Shadow Mode Launch", description: "PEPRisc shadow-mode running on live ERCPs under IRB-approved workflow", target_date: "2026-06-30", status: "Not started", workstream_id: null },
  { id: "M4", title: "Validation Complete", description: "Full validation metrics computed, failure-mode analysis done, results ready for publication", target_date: "2026-07-15", status: "Not started", workstream_id: null },
  { id: "M5", title: "Translation Ready", description: "FDA strategy documented, evidence package assembled, JHTV/Olympus ready", target_date: "2026-08-15", status: "Not started", workstream_id: null },
];

export const MOCK_RISKS: RiskItem[] = [
  { id: "RISK-001", title: "IRB amendment delays", description: "IRB amendment process may delay prospective validation timeline", severity: "High", mitigation: "Start IRB assessment early; prepare amendment language in parallel", owner: "Richu Ravikumar", status: "Open", related_task_ids: ["IRB-001", "IRB-002"] },
  { id: "RISK-002", title: "ASR accuracy insufficient for medical terminology", description: "General-purpose ASR may not achieve acceptable accuracy on ERCP-specific terminology", severity: "High", mitigation: "Evaluate multiple ASR systems; assess fine-tuning feasibility", owner: "Richu Ravikumar", status: "Open", related_task_ids: ["ASR-001", "ASR-002", "ASR-004"] },
  { id: "RISK-003", title: "Speaker diarization fails in noisy OR environment", description: "Multi-speaker cross-talk and background noise may defeat diarization", severity: "Medium", mitigation: "Test in simulated conditions first; consider directional microphones", owner: "Richu Ravikumar", status: "Open", related_task_ids: ["DIAR-001", "DIAR-002", "AUDIO-001"] },
  { id: "RISK-004", title: "HIPAA-compliant compute access delays", description: "Getting Hopkins-approved compute for ASR/PEPRisc may take longer than expected", severity: "Medium", mitigation: "Research options early; engage Hopkins IT proactively", owner: "Richu Ravikumar", status: "Open", related_task_ids: ["INFRA-001", "INFRA-002", "ASR-003"] },
  { id: "RISK-005", title: "Regulatory classification uncertainty", description: "Uncertainty about FDA CDS/SaMD classification could affect project scope", severity: "High", mitigation: "Separate platform from prediction; maintain conservative intended-use statements", owner: "Richu Ravikumar", status: "Open", related_task_ids: ["FDA-003", "FDA-004"] },
];

export const MOCK_DECISIONS: DecisionItem[] = [
  { id: "DEC-001", title: "PEPRisc output audience during shadow validation", description: "Should PEPRisc output be research-only, coordinator-facing, or clinician-facing?", decision_needed: "", owner: "PI", status: "Pending", due_date: null, related_task_ids: ["CLIN-002", "FDA-002"] },
  { id: "DEC-002", title: "Compute environment for shadow validation", description: "Where should ASR and PEPRisc inference run: local GPU, JHU Discovery, Hopkins server, or cloud?", decision_needed: "", owner: "Richu Ravikumar", status: "Pending", due_date: null, related_task_ids: ["INFRA-001", "INFRA-002"] },
  { id: "DEC-003", title: "Diarization workstream ownership", description: "Can the intern with CLSP/audio background own the diarization workstream?", decision_needed: "", owner: "Richu Ravikumar", status: "Pending", due_date: null, related_task_ids: ["DIAR-004"] },
  { id: "DEC-004", title: "PEPRisc model update strategy", description: "Should PEPRisc be updated with newer data before prospective validation?", decision_needed: "", owner: "PI", status: "Pending", due_date: null, related_task_ids: ["PEP-005"] },
];